# Generated by Django 4.1.6 on 2023-02-13 22:05

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='آدرس مقاله')),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='محتوا')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images', verbose_name='انتخاب تصویر')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='نشر')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('i', ' در حال برسی'), ('b', ' برگشت داده شده ')], max_length=1, verbose_name='وضعیت')),
                ('is_special', models.BooleanField(default=False, verbose_name='کاربر ویژه')),
            ],
        ),
        migrations.CreateModel(
            name='Authur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name=' دسته بندی')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='موقعیت')),
            ],
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آی پی')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
        ),
    ]
